/* ------------------------------------------------------------ */
/*  Generated by Enterprise Architect Version 15.2              */
/*  Created On : 02-Feb-2021 15:20:03                           */
/*  DBMS       : PostgreSQL                                     */
/*  Notes      : Script to create EA schema                     */
/* ------------------------------------------------------------ */

/* Drop Sequences for Autonumber Columns */

DROP SEQUENCE IF EXISTS id_seq
;

DROP SEQUENCE IF EXISTS propertyid_seq
;

DROP SEQUENCE IF EXISTS categoryid_seq
;

DROP SEQUENCE IF EXISTS connector_id_seq
;

DROP SEQUENCE IF EXISTS propertyid_seq
;

DROP SEQUENCE IF EXISTS datatypeid_seq
;

DROP SEQUENCE IF EXISTS diagram_id_seq
;

DROP SEQUENCE IF EXISTS instance_id_seq
;

DROP SEQUENCE IF EXISTS instance_id_seq
;

DROP SEQUENCE IF EXISTS glossaryid_seq
;

DROP SEQUENCE IF EXISTS imageid_seq
;

DROP SEQUENCE IF EXISTS issueid_seq
;

DROP SEQUENCE IF EXISTS object_id_seq
;

DROP SEQUENCE IF EXISTS propertyid_seq
;

DROP SEQUENCE IF EXISTS reqid_seq
;

DROP SEQUENCE IF EXISTS operationid_seq
;

DROP SEQUENCE IF EXISTS propertyid_seq
;

DROP SEQUENCE IF EXISTS package_id_seq
;

DROP SEQUENCE IF EXISTS paletteid_seq
;

DROP SEQUENCE IF EXISTS scriptid_seq
;

DROP SEQUENCE IF EXISTS taskid_seq
;

DROP SEQUENCE IF EXISTS trx_id_seq
;

DROP SEQUENCE IF EXISTS patternid_seq
;

/* Drop Tables */

DROP TABLE IF EXISTS t_attribute CASCADE
;

DROP TABLE IF EXISTS t_attributeconstraints CASCADE
;

DROP TABLE IF EXISTS t_attributetag CASCADE
;

DROP TABLE IF EXISTS t_authors CASCADE
;

DROP TABLE IF EXISTS t_cardinality CASCADE
;

DROP TABLE IF EXISTS t_category CASCADE
;

DROP TABLE IF EXISTS t_clients CASCADE
;

DROP TABLE IF EXISTS t_complexitytypes CASCADE
;

DROP TABLE IF EXISTS t_connector CASCADE
;

DROP TABLE IF EXISTS t_connectorconstraint CASCADE
;

DROP TABLE IF EXISTS t_connectortag CASCADE
;

DROP TABLE IF EXISTS t_connectortypes CASCADE
;

DROP TABLE IF EXISTS t_constants CASCADE
;

DROP TABLE IF EXISTS t_constrainttypes CASCADE
;

DROP TABLE IF EXISTS t_datatypes CASCADE
;

DROP TABLE IF EXISTS t_diagram CASCADE
;

DROP TABLE IF EXISTS t_diagramlinks CASCADE
;

DROP TABLE IF EXISTS t_diagramobjects CASCADE
;

DROP TABLE IF EXISTS t_diagramtypes CASCADE
;

DROP TABLE IF EXISTS t_document CASCADE
;

DROP TABLE IF EXISTS t_ecf CASCADE
;

DROP TABLE IF EXISTS t_efforttypes CASCADE
;

DROP TABLE IF EXISTS t_files CASCADE
;

DROP TABLE IF EXISTS t_genopt CASCADE
;

DROP TABLE IF EXISTS t_glossary CASCADE
;

DROP TABLE IF EXISTS t_html CASCADE
;

DROP TABLE IF EXISTS t_image CASCADE
;

DROP TABLE IF EXISTS t_implement CASCADE
;

DROP TABLE IF EXISTS t_issues CASCADE
;

DROP TABLE IF EXISTS t_lists CASCADE
;

DROP TABLE IF EXISTS t_mainttypes CASCADE
;

DROP TABLE IF EXISTS t_method CASCADE
;

DROP TABLE IF EXISTS t_metrictypes CASCADE
;

DROP TABLE IF EXISTS t_object CASCADE
;

DROP TABLE IF EXISTS t_objectconstraint CASCADE
;

DROP TABLE IF EXISTS t_objecteffort CASCADE
;

DROP TABLE IF EXISTS t_objectfiles CASCADE
;

DROP TABLE IF EXISTS t_objectmetrics CASCADE
;

DROP TABLE IF EXISTS t_objectproblems CASCADE
;

DROP TABLE IF EXISTS t_objectproperties CASCADE
;

DROP TABLE IF EXISTS t_objectrequires CASCADE
;

DROP TABLE IF EXISTS t_objectresource CASCADE
;

DROP TABLE IF EXISTS t_objectrisks CASCADE
;

DROP TABLE IF EXISTS t_objectscenarios CASCADE
;

DROP TABLE IF EXISTS t_objecttests CASCADE
;

DROP TABLE IF EXISTS t_objecttrx CASCADE
;

DROP TABLE IF EXISTS t_objecttypes CASCADE
;

DROP TABLE IF EXISTS t_ocf CASCADE
;

DROP TABLE IF EXISTS t_operation CASCADE
;

DROP TABLE IF EXISTS t_operationparams CASCADE
;

DROP TABLE IF EXISTS t_operationposts CASCADE
;

DROP TABLE IF EXISTS t_operationpres CASCADE
;

DROP TABLE IF EXISTS t_operationtag CASCADE
;

DROP TABLE IF EXISTS t_package CASCADE
;

DROP TABLE IF EXISTS t_palette CASCADE
;

DROP TABLE IF EXISTS t_paletteitem CASCADE
;

DROP TABLE IF EXISTS t_phase CASCADE
;

DROP TABLE IF EXISTS t_primitives CASCADE
;

DROP TABLE IF EXISTS t_problemtypes CASCADE
;

DROP TABLE IF EXISTS t_projectroles CASCADE
;

DROP TABLE IF EXISTS t_propertytypes CASCADE
;

DROP TABLE IF EXISTS t_requiretypes CASCADE
;

DROP TABLE IF EXISTS t_resources CASCADE
;

DROP TABLE IF EXISTS t_risktypes CASCADE
;

DROP TABLE IF EXISTS t_roleconstraint CASCADE
;

DROP TABLE IF EXISTS t_rtf CASCADE
;

DROP TABLE IF EXISTS t_rtfreport CASCADE
;

DROP TABLE IF EXISTS t_rules CASCADE
;

DROP TABLE IF EXISTS t_scenariotypes CASCADE
;

DROP TABLE IF EXISTS t_script CASCADE
;

DROP TABLE IF EXISTS t_secgroup CASCADE
;

DROP TABLE IF EXISTS t_secgrouppermission CASCADE
;

DROP TABLE IF EXISTS t_seclocks CASCADE
;

DROP TABLE IF EXISTS t_secpermission CASCADE
;

DROP TABLE IF EXISTS t_secpolicies CASCADE
;

DROP TABLE IF EXISTS t_secuser CASCADE
;

DROP TABLE IF EXISTS t_secusergroup CASCADE
;

DROP TABLE IF EXISTS t_secuserpermission CASCADE
;

DROP TABLE IF EXISTS t_snapshot CASCADE
;

DROP TABLE IF EXISTS t_statustypes CASCADE
;

DROP TABLE IF EXISTS t_stereotypes CASCADE
;

DROP TABLE IF EXISTS t_taggedvalue CASCADE
;

DROP TABLE IF EXISTS t_tasks CASCADE
;

DROP TABLE IF EXISTS t_tcf CASCADE
;

DROP TABLE IF EXISTS t_template CASCADE
;

DROP TABLE IF EXISTS t_testclass CASCADE
;

DROP TABLE IF EXISTS t_testplans CASCADE
;

DROP TABLE IF EXISTS t_testtypes CASCADE
;

DROP TABLE IF EXISTS t_trxtypes CASCADE
;

DROP TABLE IF EXISTS t_umlpattern CASCADE
;

DROP TABLE IF EXISTS t_version CASCADE
;

DROP TABLE IF EXISTS t_xref CASCADE
;

DROP TABLE IF EXISTS t_xrefsystem CASCADE
;

DROP TABLE IF EXISTS t_xrefuser CASCADE
;

DROP TABLE IF EXISTS usys_schema CASCADE
;

DROP TABLE IF EXISTS usys_system CASCADE
;

DROP TABLE IF EXISTS usysoldtables CASCADE
;

DROP TABLE IF EXISTS usysqueries CASCADE
;

DROP TABLE IF EXISTS usystables CASCADE
;

/* Drop Sequences */

DROP SEQUENCE  IF EXISTS  categoryid_seq  CASCADE
;

DROP SEQUENCE  IF EXISTS  connector_id_seq  CASCADE
;

DROP SEQUENCE  IF EXISTS  datatypeid_seq  CASCADE
;

DROP SEQUENCE  IF EXISTS  diagram_id_seq  CASCADE
;

DROP SEQUENCE  IF EXISTS  glossaryid_seq  CASCADE
;

DROP SEQUENCE  IF EXISTS  id_seq  CASCADE
;

DROP SEQUENCE  IF EXISTS  imageid_seq  CASCADE
;

DROP SEQUENCE  IF EXISTS  instance_id_seq  CASCADE
;

DROP SEQUENCE  IF EXISTS  issueid_seq  CASCADE
;

DROP SEQUENCE  IF EXISTS  object_id_seq  CASCADE
;

DROP SEQUENCE  IF EXISTS  operationid_seq  CASCADE
;

DROP SEQUENCE  IF EXISTS  package_id_seq  CASCADE
;

DROP SEQUENCE  IF EXISTS  paletteid_seq  CASCADE
;

DROP SEQUENCE  IF EXISTS  patternid_seq  CASCADE
;

DROP SEQUENCE  IF EXISTS  propertyid_seq  CASCADE
;

DROP SEQUENCE  IF EXISTS  reqid_seq  CASCADE
;

DROP SEQUENCE  IF EXISTS  scriptid_seq  CASCADE
;

DROP SEQUENCE  IF EXISTS  taskid_seq  CASCADE
;

DROP SEQUENCE  IF EXISTS  trx_id_seq  CASCADE
;

/* Create Sequences */

CREATE SEQUENCE categoryid_seq
  INCREMENT 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  START 1
  CACHE 1
;

CREATE SEQUENCE connector_id_seq
  INCREMENT 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  START 1
  CACHE 1
;

CREATE SEQUENCE datatypeid_seq
  INCREMENT 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  START 1
  CACHE 1
;

CREATE SEQUENCE diagram_id_seq
  INCREMENT 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  START 1
  CACHE 1
;

CREATE SEQUENCE glossaryid_seq
  INCREMENT 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  START 1
  CACHE 1
;

CREATE SEQUENCE id_seq
  INCREMENT 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  START 1
  CACHE 1
;

CREATE SEQUENCE imageid_seq
  INCREMENT 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  START 1
  CACHE 1
;

CREATE SEQUENCE instance_id_seq
  INCREMENT 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  START 1
  CACHE 1
;

CREATE SEQUENCE issueid_seq
  INCREMENT 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  START 1
  CACHE 1
;

CREATE SEQUENCE object_id_seq
  INCREMENT 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  START 1
  CACHE 1
;

CREATE SEQUENCE operationid_seq
  INCREMENT 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  START 1
  CACHE 1
;

CREATE SEQUENCE package_id_seq
  INCREMENT 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  START 1
  CACHE 1
;

CREATE SEQUENCE paletteid_seq
  INCREMENT 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  START 1
  CACHE 1
;

CREATE SEQUENCE patternid_seq
  INCREMENT 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  START 1
  CACHE 1
;

CREATE SEQUENCE propertyid_seq
  INCREMENT 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  START 1
  CACHE 1
;

CREATE SEQUENCE reqid_seq
  INCREMENT 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  START 1
  CACHE 1
;

CREATE SEQUENCE scriptid_seq
  INCREMENT 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  START 1
  CACHE 1
;

CREATE SEQUENCE taskid_seq
  INCREMENT 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  START 1
  CACHE 1
;

CREATE SEQUENCE trx_id_seq
  INCREMENT 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  START 1
  CACHE 1
;

----------------------------------------------
-- Create LO Domain for blobs
----------------------------------------------
CREATE DOMAIN LO AS OID;



/* Create Tables */

CREATE TABLE t_attribute
(
	object_id integer   DEFAULT 0,
	name varchar(255),
	scope varchar(50),
	stereotype varchar(50),
	containment varchar(50),
	isstatic integer   DEFAULT 0,
	iscollection integer   DEFAULT 0,
	isordered integer   DEFAULT 0,
	allowduplicates integer   DEFAULT 0,
	lowerbound varchar(50),
	upperbound varchar(50),
	container varchar(50),
	notes text,
	derived char(1),
	id integer NOT NULL   DEFAULT NEXTVAL(('id_seq'::text)::regclass),
	pos integer,
	genoption text,
	length integer,
	precision integer,
	scale integer,
	const integer,
	style varchar(255),
	classifier varchar(50),
	"Default" text,
	type varchar(255),
	ea_guid varchar(50),
	styleex text,
	CONSTRAINT pk_attribute PRIMARY KEY (id),
	CONSTRAINT uq_attribute_eaguid UNIQUE (ea_guid)
)
;
CREATE INDEX ix_attribute_name ON t_attribute (name ASC)
;
CREATE INDEX ix_attribute_objectid ON t_attribute (object_id ASC)
;
CREATE INDEX ix_attribute_classifier ON t_attribute (classifier ASC)
;
CREATE INDEX ix_attribute_type ON t_attribute (type ASC)
;


CREATE TABLE t_attributeconstraints
(
	object_id integer   DEFAULT 0,
	"Constraint" varchar(255) NOT NULL,
	attname varchar(255),
	type varchar(255),
	notes text,
	id integer NOT NULL,
	CONSTRAINT pk_attributeconstraints PRIMARY KEY (id,"Constraint")
)
;
CREATE INDEX ix_attributeconstraints_objid ON t_attributeconstraints (object_id ASC)
;


CREATE TABLE t_attributetag
(
	propertyid integer NOT NULL   DEFAULT NEXTVAL(('propertyid_seq'::text)::regclass),
	elementid integer,
	property varchar(255),
	value varchar(255),
	notes text,
	ea_guid varchar(40),
	CONSTRAINT pk_attributetag PRIMARY KEY (propertyid)
)
;
CREATE INDEX ix_attributetag_elementid ON t_attributetag (elementid ASC)
;
CREATE INDEX ix_attributetag_value ON t_attributetag (value ASC)
;
CREATE INDEX ix_attributetag_eaguid ON t_attributetag (ea_guid ASC)
;
CREATE INDEX ix_attributetag_elementidprop ON t_attributetag (elementid ASC,property ASC)
;
CREATE INDEX ix_attributetag_property ON t_attributetag (property ASC)
;


CREATE TABLE t_authors
(
	authorname varchar(255) NOT NULL,
	roles varchar(255),
	notes varchar(255),
	CONSTRAINT pk_authors PRIMARY KEY (authorname)
)
;

CREATE TABLE t_cardinality
(
	cardinality varchar(50) NOT NULL,
	CONSTRAINT pk_cardinality PRIMARY KEY (cardinality)
)
;

CREATE TABLE t_category
(
	categoryid integer NOT NULL   DEFAULT NEXTVAL(('categoryid_seq'::text)::regclass),
	name varchar(255),
	type varchar(255),
	notes text,
	CONSTRAINT pk_category PRIMARY KEY (categoryid)
)
;

CREATE TABLE t_clients
(
	name varchar(255) NOT NULL,
	organisation varchar(255),
	phone1 varchar(50),
	phone2 varchar(50),
	mobile varchar(50),
	fax varchar(50),
	email varchar(50),
	roles varchar(255),
	notes varchar(255),
	CONSTRAINT pk_clients PRIMARY KEY (name)
)
;

CREATE TABLE t_complexitytypes
(
	complexity varchar(50) NOT NULL,
	numericweight integer   DEFAULT 0,
	CONSTRAINT pk_complexitytypes PRIMARY KEY (complexity)
)
;
CREATE INDEX ix_complexitytypes_numweight ON t_complexitytypes (numericweight ASC)
;


CREATE TABLE t_connector
(
	connector_id integer NOT NULL   DEFAULT NEXTVAL(('connector_id_seq'::text)::regclass),
	name varchar(255),
	direction varchar(50),
	notes text,
	connector_type varchar(50),
	subtype varchar(50),
	sourcecard varchar(50),
	sourceaccess varchar(50),
	sourceelement varchar(50),
	destcard varchar(50),
	destaccess varchar(50),
	destelement varchar(50),
	sourcerole varchar(255),
	sourceroletype varchar(50),
	sourcerolenote text,
	sourcecontainment varchar(50),
	sourceisaggregate integer   DEFAULT 0,
	sourceisordered integer   DEFAULT 0,
	sourcequalifier varchar(50),
	destrole varchar(255),
	destroletype varchar(50),
	destrolenote text,
	destcontainment varchar(50),
	destisaggregate integer   DEFAULT 0,
	destisordered integer   DEFAULT 0,
	destqualifier varchar(50),
	start_object_id integer   DEFAULT 0,
	end_object_id integer   DEFAULT 0,
	top_start_label varchar(50),
	top_mid_label varchar(50),
	top_end_label varchar(50),
	btm_start_label varchar(50),
	btm_mid_label varchar(50),
	btm_end_label varchar(50),
	start_edge integer   DEFAULT 0,
	end_edge integer   DEFAULT 0,
	ptstartx integer   DEFAULT 0,
	ptstarty integer   DEFAULT 0,
	ptendx integer   DEFAULT 0,
	ptendy integer   DEFAULT 0,
	seqno integer   DEFAULT 0,
	headstyle integer   DEFAULT 0,
	linestyle integer   DEFAULT 0,
	routestyle integer   DEFAULT 0,
	isbold integer   DEFAULT 0,
	linecolor integer   DEFAULT 0,
	stereotype varchar(50),
	virtualinheritance char(1),
	linkaccess varchar(50),
	pdata1 varchar(255),
	pdata2 text,
	pdata3 varchar(255),
	pdata4 varchar(255),
	pdata5 text,
	diagramid integer   DEFAULT 0,
	ea_guid varchar(40),
	sourceconstraint varchar(255),
	destconstraint varchar(255),
	sourceisnavigable integer   DEFAULT 0,
	destisnavigable integer   DEFAULT 0,
	isroot integer   DEFAULT 0,
	isleaf integer   DEFAULT 0,
	isspec integer   DEFAULT 0,
	sourcechangeable varchar(12),
	destchangeable varchar(12),
	sourcets varchar(12),
	destts varchar(12),
	stateflags text,
	actionflags varchar(255),
	issignal integer   DEFAULT 0,
	isstimulus integer   DEFAULT 0,
	dispatchaction varchar(255),
	target2 integer,
	styleex text,
	sourcestereotype varchar(255),
	deststereotype varchar(255),
	sourcestyle text,
	deststyle text,
	eventflags varchar(255),
	CONSTRAINT pk_connector PRIMARY KEY (connector_id),
	CONSTRAINT uq_connector_eaguid UNIQUE (ea_guid)
)
;
CREATE INDEX ix_connector_connectortype ON t_connector (connector_type ASC)
;
CREATE INDEX ix_connector_diagramid ON t_connector (diagramid ASC)
;
CREATE INDEX ix_connector_endobjectid ON t_connector (end_object_id ASC)
;
CREATE INDEX ix_connector_start_object_id ON t_connector (start_object_id ASC)
;
CREATE INDEX ix_connector_styleex ON t_connector (styleex ASC)
;
CREATE INDEX ix_connector_endobjidconnid ON t_connector (end_object_id ASC,connector_id ASC)
;
CREATE INDEX ix_connector_startobjidconnid ON t_connector (start_object_id ASC,connector_id ASC)
;
CREATE INDEX ix_connector_seqno ON t_connector (seqno ASC)
;
CREATE INDEX ix_connector_subtype ON t_connector (subtype ASC)
;
CREATE INDEX ix_connector_pdata1 ON t_connector (pdata1 ASC)
;
CREATE INDEX ix_connector_pdata3 ON t_connector (pdata3 ASC)
;
CREATE INDEX ix_connector_pdata5 ON t_connector (pdata5 ASC)
;


CREATE TABLE t_connectorconstraint
(
	connectorid integer NOT NULL   DEFAULT 0,
	"Constraint" varchar(255) NOT NULL,
	constrainttype varchar(50),
	notes text,
	CONSTRAINT pk_connectorconstraint PRIMARY KEY (connectorid,"Constraint")
)
;
CREATE INDEX ix_connectorconstraint_constr ON t_connectorconstraint ("Constraint" ASC)
;
CREATE INDEX ix_connectorconstraint_connid ON t_connectorconstraint (connectorid ASC)
;


CREATE TABLE t_connectortag
(
	propertyid integer NOT NULL   DEFAULT NEXTVAL(('propertyid_seq'::text)::regclass),
	elementid integer,
	property varchar(255),
	value varchar(255),
	notes text,
	ea_guid varchar(40),
	CONSTRAINT pk_connectortag PRIMARY KEY (propertyid)
)
;
CREATE INDEX ix_connectortag_elementid ON t_connectortag (elementid ASC)
;
CREATE INDEX ix_connectortag_property ON t_connectortag (property ASC)
;
CREATE INDEX ix_connectortag_value ON t_connectortag (value ASC)
;
CREATE INDEX ix_connectortag_eaguid ON t_connectortag (ea_guid ASC)
;


CREATE TABLE t_connectortypes
(
	connector_type varchar(50) NOT NULL,
	description varchar(50),
	CONSTRAINT pk_connectortypes PRIMARY KEY (connector_type)
)
;

CREATE TABLE t_constants
(
	constantname varchar(50) NOT NULL,
	constantvalue varchar(255),
	CONSTRAINT pk_constants PRIMARY KEY (constantname)
)
;

CREATE TABLE t_constrainttypes
(
	"Constraint" varchar(16) NOT NULL,
	description varchar(50),
	notes text,
	CONSTRAINT pk_constrainttypes PRIMARY KEY ("Constraint")
)
;

CREATE TABLE t_datatypes
(
	type varchar(50),
	productname varchar(50),
	datatype varchar(50),
	size integer,
	maxlen integer,
	maxprec integer,
	maxscale integer   DEFAULT 0,
	defaultlen integer,
	defaultprec integer,
	defaultscale integer,
	"User" integer,
	pdata1 varchar(255),
	pdata2 varchar(255),
	pdata3 varchar(255),
	pdata4 varchar(255),
	haslength varchar(50),
	generictype varchar(255),
	datatypeid integer NOT NULL   DEFAULT NEXTVAL(('datatypeid_seq'::text)::regclass),
	CONSTRAINT pk_datatypes PRIMARY KEY (datatypeid)
)
;
CREATE INDEX ix_datatypes_productname ON t_datatypes (productname ASC)
;
CREATE INDEX ix_datatypes_datatype ON t_datatypes (datatype ASC)
;


CREATE TABLE t_diagram
(
	diagram_id integer NOT NULL   DEFAULT NEXTVAL(('diagram_id_seq'::text)::regclass),
	package_id integer   DEFAULT 1,
	parentid integer   DEFAULT 0,
	diagram_type varchar(50),
	name varchar(255),
	version varchar(50)   DEFAULT '1.0',
	author varchar(255),
	showdetails integer   DEFAULT 0,
	notes text,
	stereotype varchar(50),
	attpub integer NOT NULL   DEFAULT 1,
	attpri integer NOT NULL   DEFAULT 1,
	attpro integer NOT NULL   DEFAULT 1,
	orientation char(1)   DEFAULT 'P',
	cx integer   DEFAULT 0,
	cy integer   DEFAULT 0,
	scale integer   DEFAULT 100,
	createddate timestamp without time zone   DEFAULT now(),
	modifieddate timestamp without time zone   DEFAULT now(),
	htmlpath varchar(255),
	showforeign integer NOT NULL   DEFAULT 1,
	showborder integer NOT NULL   DEFAULT 1,
	showpackagecontents integer NOT NULL   DEFAULT 1,
	pdata varchar(255),
	locked integer NOT NULL   DEFAULT 0,
	ea_guid varchar(40),
	tpos integer,
	swimlanes varchar(255),
	styleex text,
	CONSTRAINT pk_diagram PRIMARY KEY (diagram_id),
	CONSTRAINT uq_diagram_eaguid UNIQUE (ea_guid)
)
;
CREATE INDEX ix_diagram_diagramtype ON t_diagram (diagram_type ASC)
;
CREATE INDEX ix_diagram_packageid ON t_diagram (package_id ASC)
;
CREATE INDEX ix_diagram_parentid ON t_diagram (parentid ASC)
;


CREATE TABLE t_diagramlinks
(
	diagramid integer,
	connectorid integer,
	geometry text,
	style varchar(255),
	hidden integer NOT NULL   DEFAULT 0,
	path varchar(255),
	instance_id integer NOT NULL   DEFAULT NEXTVAL(('instance_id_seq'::text)::regclass),
	CONSTRAINT pk_diagramlinks PRIMARY KEY (instance_id)
)
;
CREATE INDEX ix_diagramlinks_connectorid ON t_diagramlinks (connectorid ASC)
;
CREATE INDEX ix_diagramlinks_diagramid ON t_diagramlinks (diagramid ASC)
;


CREATE TABLE t_diagramobjects
(
	diagram_id integer   DEFAULT 0,
	object_id integer   DEFAULT 0,
	recttop integer   DEFAULT 0,
	rectleft integer   DEFAULT 0,
	rectright integer   DEFAULT 0,
	rectbottom integer   DEFAULT 0,
	sequence integer   DEFAULT 0,
	objectstyle varchar(255),
	instance_id integer NOT NULL   DEFAULT NEXTVAL(('instance_id_seq'::text)::regclass),
	CONSTRAINT pk_diagramobjects PRIMARY KEY (instance_id)
)
;
CREATE INDEX ix_diagramobjects_diagramid ON t_diagramobjects (diagram_id ASC)
;
CREATE INDEX ix_diagramobjects_objectid ON t_diagramobjects (object_id ASC)
;
CREATE INDEX ix_diagramobjects_sequence ON t_diagramobjects (sequence ASC)
;


CREATE TABLE t_diagramtypes
(
	diagram_type varchar(50) NOT NULL,
	name varchar(255),
	package_id integer   DEFAULT 0,
	CONSTRAINT pk_diagramtypes PRIMARY KEY (diagram_type)
)
;
CREATE INDEX ix_diagramtypes_packageid ON t_diagramtypes (package_id ASC)
;


CREATE TABLE t_document
(
	docid varchar(40) NOT NULL,
	docname varchar(100),
	notes varchar(255),
	style varchar(255),
	elementid varchar(40) NOT NULL,
	elementtype varchar(50) NOT NULL,
	strcontent text,
	bincontent bytea,
	doctype varchar(100),
	author varchar(255),
	version varchar(50),
	isactive integer   DEFAULT 1,
	sequence integer   DEFAULT 0,
	docdate timestamp without time zone,
	CONSTRAINT pk_document PRIMARY KEY (docid)
)
;
CREATE INDEX ix_document_elementid ON t_document (elementid ASC)
;
CREATE INDEX ix_document_author ON t_document (author ASC)
;
CREATE INDEX ix_document_doctype ON t_document (doctype ASC)
;
CREATE INDEX ix_document_style ON t_document (style ASC)
;
CREATE INDEX ix_document_version ON t_document (version ASC)
;


CREATE TABLE t_ecf
(
	ecfid varchar(12) NOT NULL,
	description varchar(50),
	weight real   DEFAULT 1,
	value real   DEFAULT 0,
	notes varchar(255),
	CONSTRAINT pk_ecf PRIMARY KEY (ecfid)
)
;
CREATE INDEX ix_ecf_weight ON t_ecf (weight ASC)
;


CREATE TABLE t_efforttypes
(
	efforttype varchar(12) NOT NULL,
	description varchar(255),
	numericweight real   DEFAULT 0,
	notes varchar(255),
	CONSTRAINT pk_efforttypes PRIMARY KEY (efforttype)
)
;
CREATE INDEX ix_efforttypes_numericweight ON t_efforttypes (numericweight ASC)
;


CREATE TABLE t_files
(
	fileid varchar(50) NOT NULL,
	appliesto varchar(50) NOT NULL,
	category varchar(100) NOT NULL,
	name varchar(150) NOT NULL,
	file varchar(255),
	notes text,
	filedate timestamp without time zone,
	filesize integer,
	CONSTRAINT pk_files PRIMARY KEY (fileid)
)
;
CREATE INDEX ix_files_appliesto ON t_files (appliesto ASC)
;
CREATE INDEX ix_files_appliestoname ON t_files (appliesto ASC,name ASC)
;
CREATE INDEX ix_files_appliestonamesize ON t_files (appliesto ASC,name ASC,filesize ASC)
;
CREATE INDEX ix_files_appliestonamedatesize ON t_files (appliesto ASC,name ASC,filedate 
ASC,filesize ASC)
;
CREATE INDEX ix_files_category ON t_files (category ASC)
;
CREATE INDEX ix_files_filesize ON t_files (filesize ASC)
;
CREATE INDEX ix_files_name ON t_files (name ASC)
;


CREATE TABLE t_genopt
(
	appliesto varchar(12),
	option text
)
;

CREATE TABLE t_glossary
(
	term varchar(255),
	type varchar(255),
	meaning text,
	glossaryid integer NOT NULL   DEFAULT NEXTVAL(('glossaryid_seq'::text)::regclass),
	CONSTRAINT pk_glossary PRIMARY KEY (glossaryid)
)
;
CREATE INDEX idx_glossary_term ON t_glossary (term ASC)
;
CREATE INDEX idx_glossary_type ON t_glossary (type ASC)
;


CREATE TABLE t_html
(
	type varchar(50),
	template text
)
;

CREATE TABLE t_image
(
	imageid integer NOT NULL   DEFAULT NEXTVAL(('imageid_seq'::text)::regclass),
	name varchar(255),
	type varchar(255),
	image bytea,
	CONSTRAINT pk_image PRIMARY KEY (imageid)
)
;

CREATE TABLE t_implement
(
	type varchar(50)
)
;

CREATE TABLE t_issues
(
	issue varchar(255),
	issuedate timestamp without time zone,
	owner varchar(255),
	status varchar(50),
	notes text,
	resolver varchar(255),
	dateresolved timestamp without time zone,
	resolution text,
	issueid integer NOT NULL   DEFAULT NEXTVAL(('issueid_seq'::text)::regclass),
	category varchar(255),
	priority varchar(50),
	severity varchar(50),
	issuetype varchar(100),
	CONSTRAINT pk_issues PRIMARY KEY (issueid)
)
;

CREATE TABLE t_lists
(
	listid varchar(50) NOT NULL,
	category varchar(100) NOT NULL,
	name varchar(150) NOT NULL,
	nval integer,
	notes text,
	CONSTRAINT pk_lists PRIMARY KEY (listid)
)
;

CREATE TABLE t_mainttypes
(
	mainttype varchar(12) NOT NULL,
	description varchar(50),
	numericweight real   DEFAULT 1,
	notes varchar(255),
	CONSTRAINT pk_mainttypes PRIMARY KEY (mainttype)
)
;
CREATE INDEX ix_maintyypes_numericweight ON t_mainttypes (numericweight ASC)
;


CREATE TABLE t_method
(
	object_id integer NOT NULL   DEFAULT 0,
	name varchar(255) NOT NULL,
	scope varchar(50),
	type varchar(50),
	CONSTRAINT pk_method PRIMARY KEY (object_id,name)
)
;
CREATE INDEX ix_method_objectid ON t_method (object_id ASC)
;


CREATE TABLE t_metrictypes
(
	metric varchar(12) NOT NULL,
	description varchar(50),
	numericweight real   DEFAULT 1,
	notes varchar(255),
	CONSTRAINT pk_metrictypes PRIMARY KEY (metric)
)
;
CREATE INDEX ix_metrictypes_numericweight ON t_metrictypes (numericweight ASC)
;


CREATE TABLE t_object
(
	object_id integer NOT NULL   DEFAULT NEXTVAL(('object_id_seq'::text)::regclass),
	object_type varchar(255),
	diagram_id integer   DEFAULT 0,
	name varchar(255),
	alias varchar(255),
	author varchar(255),
	version varchar(50)   DEFAULT '1.0',
	note text,
	package_id integer   DEFAULT 0,
	stereotype varchar(255),
	ntype integer   DEFAULT 0,
	complexity varchar(50)   DEFAULT '2',
	effort integer   DEFAULT 0,
	style varchar(255),
	backcolor integer   DEFAULT 0,
	borderstyle integer   DEFAULT 0,
	borderwidth integer   DEFAULT 0,
	fontcolor integer   DEFAULT 0,
	bordercolor integer   DEFAULT 0,
	createddate timestamp without time zone   DEFAULT now(),
	modifieddate timestamp without time zone   DEFAULT now(),
	status varchar(50),
	abstract char(1),
	tagged integer   DEFAULT 0,
	pdata1 varchar(255),
	pdata2 text,
	pdata3 text,
	pdata4 text,
	pdata5 varchar(255),
	concurrency varchar(50),
	visibility varchar(50),
	persistence varchar(50),
	cardinality varchar(50),
	gentype varchar(50),
	genfile varchar(255),
	header1 text,
	header2 text,
	phase varchar(50),
	scope varchar(25),
	genoption text,
	genlinks text,
	classifier integer,
	ea_guid varchar(40),
	parentid integer,
	runstate text,
	classifier_guid varchar(40),
	tpos integer,
	isroot integer   DEFAULT 0,
	isleaf integer   DEFAULT 0,
	isspec integer   DEFAULT 0,
	isactive integer   DEFAULT 0,
	stateflags varchar(255),
	packageflags varchar(255),
	multiplicity varchar(50),
	styleex text,
	actionflags varchar(255),
	eventflags varchar(255),
	CONSTRAINT pk_object PRIMARY KEY (object_id),
	CONSTRAINT uq_object_eaguid UNIQUE (ea_guid)
)
;
CREATE INDEX ix_object_classifier ON t_object (classifier ASC)
;
CREATE INDEX ix_object_classifierguid ON t_object (classifier_guid ASC)
;
CREATE INDEX ix_object_genlinks ON t_object (genlinks ASC)
;
CREATE INDEX ix_object_ntype ON t_object (ntype ASC)
;
CREATE INDEX ix_object_objecttype ON t_object (object_type ASC)
;
CREATE INDEX ix_object_packageid ON t_object (package_id ASC)
;
CREATE INDEX ix_object_parentid ON t_object (parentid ASC)
;
CREATE INDEX ix_object_pdata1 ON t_object (pdata1 ASC)
;
CREATE INDEX ix_object_eventflags ON t_object (eventflags ASC)
;
CREATE INDEX ix_object_name ON t_object (name ASC)
;
CREATE INDEX ix_object_pkgidpdata1class ON t_object (package_id ASC,pdata1 ASC,classifier ASC)
;
CREATE INDEX ix_object_eaguidclassifier ON t_object (ea_guid ASC,classifier ASC)
;
CREATE INDEX ix_object_pdata2 ON t_object (pdata2 ASC)
;
CREATE INDEX ix_object_pdata3 ON t_object (pdata3 ASC)
;
CREATE INDEX ix_object_pdata4 ON t_object (pdata4 ASC)
;
CREATE INDEX ix_object_pdata5 ON t_object (pdata5 ASC)
;


CREATE TABLE t_objectconstraint
(
	object_id integer NOT NULL   DEFAULT 0,
	"Constraint" varchar(255) NOT NULL,
	constrainttype varchar(30) NOT NULL,
	weight real   DEFAULT 0,
	notes text,
	status varchar(50),
	CONSTRAINT pk_objectconstraint PRIMARY KEY (object_id,"Constraint",constrainttype)
)
;
CREATE INDEX ix_objectconstraint_constr ON t_objectconstraint ("Constraint" ASC)
;
CREATE INDEX ix_objectconstraint_objectid ON t_objectconstraint (object_id ASC)
;


CREATE TABLE t_objecteffort
(
	object_id integer NOT NULL   DEFAULT 0,
	effort varchar(255) NOT NULL,
	efforttype varchar(12),
	evalue real   DEFAULT 0,
	notes text,
	CONSTRAINT pk_objecteffort PRIMARY KEY (object_id,effort)
)
;
CREATE INDEX ix_objecteffort_objectid ON t_objecteffort (object_id ASC)
;


CREATE TABLE t_objectfiles
(
	object_id integer NOT NULL   DEFAULT 0,
	filename varchar(255) NOT NULL,
	type varchar(50),
	note text,
	filesize varchar(255),
	filedate varchar(255),
	CONSTRAINT pk_objectfiles PRIMARY KEY (object_id,filename)
)
;

CREATE TABLE t_objectmetrics
(
	object_id integer NOT NULL   DEFAULT 0,
	metric varchar(255) NOT NULL,
	metrictype varchar(12),
	evalue real   DEFAULT 1,
	notes text,
	CONSTRAINT pk_objectmetrics PRIMARY KEY (object_id,metric)
)
;
CREATE INDEX ix_objectmetrics_metrictype ON t_objectmetrics (metrictype ASC)
;
CREATE INDEX ix_objectmetrics_objectid ON t_objectmetrics (object_id ASC)
;
CREATE INDEX ix_objectmetrics_metric ON t_objectmetrics (metric ASC)
;


CREATE TABLE t_objectproblems
(
	object_id integer NOT NULL   DEFAULT 0,
	problem varchar(255) NOT NULL,
	problemtype varchar(255) NOT NULL,
	datereported date,
	status varchar(50),
	problemnotes text,
	reportedby varchar(255),
	resolvedby varchar(255),
	dateresolved date,
	version varchar(50),
	resolvernotes text,
	priority varchar(50),
	severity varchar(50),
	CONSTRAINT pk_objectproblems PRIMARY KEY (object_id,problem,problemtype)
)
;
CREATE INDEX ix_objectproblems_objectid ON t_objectproblems (object_id ASC)
;
CREATE INDEX ix_objectproblems_problem ON t_objectproblems (problem ASC)
;


CREATE TABLE t_objectproperties
(
	propertyid integer NOT NULL   DEFAULT NEXTVAL(('propertyid_seq'::text)::regclass),
	object_id integer   DEFAULT 0,
	property varchar(255),
	value varchar(255),
	notes text,
	ea_guid varchar(40),
	CONSTRAINT pk_objectproperties PRIMARY KEY (propertyid)
)
;
CREATE INDEX ix_objectproperties_objectid ON t_objectproperties (object_id ASC)
;
CREATE INDEX ix_objectproperties_value ON t_objectproperties (value ASC)
;
CREATE INDEX ix_objectproperties_property ON t_objectproperties (property ASC)
;
CREATE INDEX ix_objectproperties_objidprop ON t_objectproperties (object_id ASC,property ASC)
;
CREATE INDEX ix_objectproperties_eaguid ON t_objectproperties (ea_guid ASC)
;


CREATE TABLE t_objectrequires
(
	reqid integer NOT NULL   DEFAULT NEXTVAL(('reqid_seq'::text)::regclass),
	object_id integer   DEFAULT 0,
	requirement varchar(255),
	reqtype varchar(255),
	status varchar(50),
	notes text,
	stability varchar(50),
	difficulty varchar(50),
	priority varchar(50),
	lastupdate timestamp without time zone   DEFAULT now(),
	CONSTRAINT pk_objectrequires PRIMARY KEY (reqid)
)
;
CREATE INDEX ix_objectrequires_objectid ON t_objectrequires (object_id ASC)
;
CREATE INDEX ix_objectrequires_requirement ON t_objectrequires (requirement ASC)
;


CREATE TABLE t_objectresource
(
	object_id integer NOT NULL   DEFAULT 0,
	resource varchar(255) NOT NULL,
	role varchar(255) NOT NULL,
	time real   DEFAULT 0,
	notes text,
	percentcomplete smallint   DEFAULT 0,
	datestart date,
	dateend date,
	history text,
	expectedhours integer,
	actualhours integer,
	CONSTRAINT pk_objectresource PRIMARY KEY (object_id,resource,role)
)
;
CREATE INDEX ix_objectresource_objectid ON t_objectresource (object_id ASC)
;


CREATE TABLE t_objectrisks
(
	object_id integer NOT NULL   DEFAULT 0,
	risk varchar(255) NOT NULL,
	risktype varchar(12),
	evalue real   DEFAULT 0,
	notes text,
	CONSTRAINT pk_objectrisks PRIMARY KEY (object_id,risk)
)
;
CREATE INDEX ix_objectrisks_objectid ON t_objectrisks (object_id ASC)
;


CREATE TABLE t_objectscenarios
(
	object_id integer NOT NULL   DEFAULT 0,
	scenario varchar(255) NOT NULL,
	scenariotype varchar(12),
	evalue real   DEFAULT 0,
	notes text,
	ea_guid varchar(40) NOT NULL,
	xmlcontent text,
	CONSTRAINT pk_objectscenarios PRIMARY KEY (object_id,scenario)
)
;
CREATE INDEX ix_objectscenarios_objectid ON t_objectscenarios (object_id ASC)
;
CREATE INDEX ix_objectscenarios_oidevalscen ON t_objectscenarios (object_id ASC,evalue ASC,scenario ASC)
;


CREATE TABLE t_objecttests
(
	object_id integer NOT NULL   DEFAULT 0,
	test varchar(255) NOT NULL,
	testclass integer NOT NULL   DEFAULT 0,
	testtype varchar(50),
	notes text,
	inputdata text,
	acceptancecriteria text,
	status varchar(32),
	daterun date   DEFAULT now(),
	results text,
	runby varchar(255),
	checkby varchar(255),
	CONSTRAINT pk_objecttests PRIMARY KEY (object_id,test,testclass)
)
;
CREATE INDEX ix_objecttests_objectid ON t_objecttests (object_id ASC)
;
CREATE INDEX ix_objecttexts_objidtclassstat ON t_objecttests (object_id ASC,testclass ASC,status ASC)
;


CREATE TABLE t_objecttrx
(
	object_id integer NOT NULL   DEFAULT 0,
	trx varchar(255) NOT NULL,
	trxtype varchar(12) NOT NULL,
	weight real   DEFAULT 0,
	notes text,
	CONSTRAINT pk_objecttrx PRIMARY KEY (object_id,trx,trxtype)
)
;
CREATE INDEX ix_objecttrx_trx ON t_objecttrx (trx ASC)
;
CREATE INDEX ix_objecttrx_objectid ON t_objecttrx (object_id ASC)
;


CREATE TABLE t_objecttypes
(
	object_type varchar(50) NOT NULL,
	description varchar(255),
	designobject integer NOT NULL   DEFAULT 0,
	imageid smallint   DEFAULT 0,
	CONSTRAINT pk_objecttypes PRIMARY KEY (object_type)
)
;
CREATE INDEX ix_objecttypes_imageid ON t_objecttypes (imageid ASC)
;


CREATE TABLE t_ocf
(
	objecttype varchar(50),
	complexityweight real   DEFAULT 0
)
;

CREATE TABLE t_operation
(
	operationid integer NOT NULL   DEFAULT NEXTVAL(('operationid_seq'::text)::regclass),
	object_id integer   DEFAULT 0,
	name varchar(255),
	scope varchar(50),
	type varchar(255),
	returnarray char(1),
	stereotype varchar(50),
	isstatic char(1),
	concurrency varchar(50),
	notes text,
	behaviour text,
	abstract char(1),
	genoption text,
	synchronized char(1),
	pos integer,
	const integer,
	style varchar(255),
	pure integer NOT NULL   DEFAULT 0,
	throws varchar(255),
	classifier varchar(50),
	code text,
	isroot integer   DEFAULT 0,
	isleaf integer   DEFAULT 0,
	isquery integer   DEFAULT 0,
	stateflags varchar(255),
	ea_guid varchar(50),
	styleex text,
	CONSTRAINT pk_operation PRIMARY KEY (operationid),
	CONSTRAINT uq_operation_eaguid UNIQUE (ea_guid)
)
;
CREATE INDEX ix_operation_name ON t_operation (name ASC)
;
CREATE INDEX ix_operation_objectid ON t_operation (object_id ASC)
;
CREATE INDEX ix_operation_classifier ON t_operation (classifier ASC)
;
CREATE INDEX ix_operation_objectidopid ON t_operation (object_id ASC,operationid ASC)
;


CREATE TABLE t_operationparams
(
	operationid integer NOT NULL   DEFAULT 0,
	name varchar(255) NOT NULL,
	type varchar(255),
	"Default" varchar(255),
	notes text,
	pos integer,
	const integer   DEFAULT 0,
	style varchar(255),
	kind varchar(12),
	classifier varchar(50),
	ea_guid varchar(50),
	styleex text,
	CONSTRAINT pk_operationparams PRIMARY KEY (operationid,name),
	CONSTRAINT uq_operationparams_eaguid UNIQUE (ea_guid)
)
;
CREATE INDEX ix_operationparams_opid ON t_operationparams (operationid ASC)
;
CREATE INDEX ix_operationparams_opidpos ON t_operationparams (operationid ASC,pos ASC)
;
CREATE INDEX ix_operationparams_classifier ON t_operationparams (classifier ASC)
;


CREATE TABLE t_operationposts
(
	operationid integer NOT NULL   DEFAULT 0,
	postcondition varchar(255) NOT NULL,
	type varchar(255),
	notes text,
	CONSTRAINT pk_operationposts PRIMARY KEY (operationid,postcondition)
)
;
CREATE INDEX ix_operationposts_operationid ON t_operationposts (operationid ASC)
;


CREATE TABLE t_operationpres
(
	operationid integer NOT NULL   DEFAULT 0,
	precondition varchar(255) NOT NULL,
	type varchar(50),
	notes text,
	CONSTRAINT pk_operationpres PRIMARY KEY (operationid,precondition)
)
;
CREATE INDEX ix_operationpres_operationid ON t_operationpres (operationid ASC)
;


CREATE TABLE t_operationtag
(
	propertyid integer NOT NULL   DEFAULT NEXTVAL(('propertyid_seq'::text)::regclass),
	elementid integer,
	property varchar(255),
	value varchar(255),
	notes text,
	ea_guid varchar(40),
	CONSTRAINT pk_operationtag PRIMARY KEY (propertyid)
)
;
CREATE INDEX ix_operationtag_elementid ON t_operationtag (elementid ASC)
;
CREATE INDEX ix_operationtag_value ON t_operationtag (value ASC)
;
CREATE INDEX ix_operationtag_eaguid ON t_operationtag (ea_guid ASC)
;
CREATE INDEX ix_operationtag_elementidprop ON t_operationtag (elementid ASC,property ASC)
;
CREATE INDEX ix_operationtag_property ON t_operationtag (property ASC)
;


CREATE TABLE t_package
(
	package_id integer NOT NULL   DEFAULT NEXTVAL(('package_id_seq'::text)::regclass),
	name varchar(255),
	parent_id integer   DEFAULT 0,
	createddate timestamp without time zone   DEFAULT now(),
	modifieddate timestamp without time zone   DEFAULT now(),
	notes text,
	ea_guid varchar(40),
	xmlpath varchar(255),
	iscontrolled integer   DEFAULT 0,
	lastloaddate timestamp without time zone,
	lastsavedate timestamp without time zone,
	version varchar(50),
	protected integer   DEFAULT 0,
	pkgowner varchar(255),
	umlversion varchar(50),
	usedtd integer   DEFAULT 0,
	logxml integer   DEFAULT 0,
	codepath varchar(255),
	namespace varchar(50),
	tpos integer,
	packageflags varchar(255),
	batchsave integer,
	batchload integer,
	CONSTRAINT pk_package PRIMARY KEY (package_id),
	CONSTRAINT uq_package_eaguid UNIQUE (ea_guid)
)
;
CREATE INDEX ix_package_parentid ON t_package (parent_id ASC)
;
CREATE INDEX ix_package_name ON t_package (name ASC)
;


CREATE TABLE t_palette
(
	paletteid integer NOT NULL   DEFAULT NEXTVAL(('paletteid_seq'::text)::regclass),
	name varchar(255),
	type varchar(255),
	CONSTRAINT pk_palette PRIMARY KEY (paletteid)
)
;

CREATE TABLE t_paletteitem
(
	paletteid integer,
	itemid integer
)
;

CREATE TABLE t_phase
(
	phaseid varchar(40) NOT NULL,
	phasename varchar(100) NOT NULL,
	phasenotes text,
	phasestyle varchar(255),
	startdate timestamp without time zone,
	enddate timestamp without time zone,
	phasecontent text,
	CONSTRAINT pk_phase PRIMARY KEY (phaseid)
)
;

CREATE TABLE t_primitives
(
	datatype varchar(50) NOT NULL,
	description varchar(50),
	CONSTRAINT pk_primitives PRIMARY KEY (datatype)
)
;

CREATE TABLE t_problemtypes
(
	problemtype varchar(12) NOT NULL,
	description varchar(255),
	numericweight real   DEFAULT 1,
	notes varchar(255),
	CONSTRAINT pk_problemtypes PRIMARY KEY (problemtype)
)
;
CREATE INDEX ix_problemtypes_numericweight ON t_problemtypes (numericweight ASC)
;


CREATE TABLE t_projectroles
(
	role varchar(255) NOT NULL,
	description varchar(255),
	notes text,
	CONSTRAINT pk_projectroles PRIMARY KEY (role)
)
;

CREATE TABLE t_propertytypes
(
	property varchar(50) NOT NULL,
	description varchar(50),
	notes text,
	CONSTRAINT pk_propertytypes PRIMARY KEY (property)
)
;

CREATE TABLE t_requiretypes
(
	requirement varchar(12) NOT NULL,
	description varchar(50),
	numericweight real   DEFAULT 1,
	notes varchar(255),
	CONSTRAINT pk_requiretypes PRIMARY KEY (requirement)
)
;
CREATE INDEX ix_requiretypes_numericweight ON t_requiretypes (numericweight ASC)
;


CREATE TABLE t_resources
(
	name varchar(255) NOT NULL,
	organisation varchar(255),
	phone1 varchar(50),
	phone2 varchar(50),
	mobile varchar(50),
	fax varchar(50),
	email varchar(255),
	roles varchar(255),
	notes varchar(255),
	CONSTRAINT pk_resources PRIMARY KEY (name)
)
;

CREATE TABLE t_risktypes
(
	risk varchar(12) NOT NULL,
	description varchar(50),
	numericweight real   DEFAULT 0,
	notes varchar(255),
	CONSTRAINT pk_risktypes PRIMARY KEY (risk)
)
;
CREATE INDEX ix_risktypes_numericweight ON t_risktypes (numericweight ASC)
;


CREATE TABLE t_roleconstraint
(
	connectorid integer NOT NULL   DEFAULT 0,
	"Constraint" varchar(255) NOT NULL,
	connectorend varchar(50) NOT NULL,
	constrainttype varchar(12) NOT NULL,
	notes text,
	CONSTRAINT pk_roleconstraint PRIMARY KEY (connectorid,"Constraint",connectorend,constrainttype)
)
;
CREATE INDEX ix_roleconstraint_constraint ON t_roleconstraint ("Constraint" ASC)
;
CREATE INDEX ix_roleconstraint_connectorid ON t_roleconstraint (connectorid ASC)
;


CREATE TABLE t_rtf
(
	type varchar(50),
	template text
)
;

CREATE TABLE t_rtfreport
(
	templateid varchar(200) NOT NULL,
	rootpackage integer   DEFAULT 0,
	filename varchar(255),
	details integer   DEFAULT 0,
	processchildren integer   DEFAULT 0,
	showdiagrams integer   DEFAULT 0,
	heading varchar(255),
	requirements integer   DEFAULT 0,
	associations integer   DEFAULT 0,
	scenarios integer   DEFAULT 0,
	childdiagrams integer   DEFAULT 0,
	attributes integer   DEFAULT 0,
	methods integer   DEFAULT 0,
	imagetype integer   DEFAULT 0,
	paging integer   DEFAULT 0,
	intro text,
	resources integer   DEFAULT 1,
	constraints integer   DEFAULT 1,
	tagged integer   DEFAULT 0,
	showtag integer   DEFAULT 0,
	showalias integer   DEFAULT 0,
	pdata1 varchar(255),
	pdata2 varchar(255),
	pdata3 varchar(255),
	pdata4 text,
	CONSTRAINT pk_rtfreport PRIMARY KEY (templateid)
)
;

CREATE TABLE t_rules
(
	ruleid varchar(50) NOT NULL,
	rulename varchar(255) NOT NULL,
	ruletype varchar(255) NOT NULL,
	ruleactive integer,
	errormsg varchar(255),
	flags varchar(255),
	ruleocl text,
	rulexml text,
	notes text,
	CONSTRAINT pk_rules PRIMARY KEY (ruleid)
)
;

CREATE TABLE t_scenariotypes
(
	scenariotype varchar(12) NOT NULL,
	description varchar(50),
	numericweight real   DEFAULT 1,
	notes varchar(255),
	CONSTRAINT pk_scenariotypes PRIMARY KEY (scenariotype)
)
;
CREATE INDEX ix_scenariotypes_numericweight ON t_scenariotypes (numericweight ASC)
;


CREATE TABLE t_script
(
	scriptid integer NOT NULL   DEFAULT NEXTVAL(('scriptid_seq'::text)::regclass),
	scriptcategory varchar(100),
	scriptname varchar(150),
	scriptauthor varchar(255),
	notes text,
	script text,
	CONSTRAINT pk_script PRIMARY KEY (scriptid)
)
;
CREATE INDEX ix_script_scriptcategory ON t_script (scriptcategory ASC)
;


CREATE TABLE t_secgroup
(
	groupid varchar(40) NOT NULL,
	groupname varchar(32) NOT NULL,
	description varchar(100),
	CONSTRAINT pk_secgroup PRIMARY KEY (groupid)
)
;

CREATE TABLE t_secgrouppermission
(
	groupid varchar(40) NOT NULL,
	permissionid integer NOT NULL,
	CONSTRAINT pk_secgrouppermission PRIMARY KEY (groupid,permissionid)
)
;

CREATE TABLE t_seclocks
(
	userid varchar(40) NOT NULL,
	groupid varchar(40),
	entitytype varchar(32) NOT NULL,
	entityid varchar(40) NOT NULL,
	timestamp timestamp without time zone NOT NULL,
	locktype varchar(255),
	CONSTRAINT pk_seclocks PRIMARY KEY (entityid)
)
;
CREATE INDEX ix_seclocks_entityiduserid ON t_seclocks (entityid ASC,userid ASC)
;
CREATE INDEX ix_seclocks_entityidtype ON t_seclocks (entityid ASC,entitytype ASC)
;
CREATE INDEX ix_seclocks_entityidusrtype ON t_seclocks (entityid ASC,userid ASC,entitytype ASC)
;
CREATE INDEX ix_seclocks_groupid ON t_seclocks (groupid ASC)
;
CREATE INDEX ix_seclocks_groupiduserid ON t_seclocks (groupid ASC,userid ASC)
;


CREATE TABLE t_secpermission
(
	permissionid integer NOT NULL,
	permissionname varchar(50) NOT NULL,
	CONSTRAINT pk_secpermission PRIMARY KEY (permissionid)
)
;

CREATE TABLE t_secpolicies
(
	property varchar(100) NOT NULL,
	value varchar(255) NOT NULL,
	CONSTRAINT pk_secpolicies PRIMARY KEY (property)
)
;

CREATE TABLE t_secuser
(
	userid varchar(40) NOT NULL,
	userlogin varchar(255) NOT NULL,
	firstname varchar(50) NOT NULL,
	surname varchar(50) NOT NULL,
	department varchar(50),
	password varchar(12),
	CONSTRAINT pk_secuser PRIMARY KEY (userid)
)
;

CREATE TABLE t_secusergroup
(
	userid varchar(40) NOT NULL,
	groupid varchar(40) NOT NULL,
	CONSTRAINT pk_secusergroup PRIMARY KEY (userid,groupid)
)
;

CREATE TABLE t_secuserpermission
(
	userid varchar(40) NOT NULL,
	permissionid integer NOT NULL,
	CONSTRAINT pk_secuserpermission PRIMARY KEY (userid,permissionid)
)
;

CREATE TABLE t_snapshot
(
	snapshotid varchar(40) NOT NULL,
	seriesid varchar(40) NOT NULL,
	position integer,
	snapshotname varchar(100),
	notes text,
	style varchar(255),
	elementid varchar(40) NOT NULL,
	elementtype varchar(50) NOT NULL,
	strcontent text,
	bincontent1 bytea,
	bincontent2 bytea,
	CONSTRAINT pk_snapshot PRIMARY KEY (snapshotid)
)
;
CREATE INDEX ix_snapshot_position ON t_snapshot (position ASC)
;
CREATE INDEX ix_snapshot_seriesid ON t_snapshot (seriesid ASC)
;


CREATE TABLE t_statustypes
(
	status varchar(50) NOT NULL,
	description varchar(50),
	CONSTRAINT pk_statustypes PRIMARY KEY (status)
)
;

CREATE TABLE t_stereotypes
(
	stereotype varchar(255) NOT NULL,
	appliesto varchar(255) NOT NULL,
	description varchar(255),
	mfenabled integer   DEFAULT 0,
	mfpath varchar(255),
	metafile bytea,
	style text,
	ea_guid varchar(50),
	visualtype varchar(100),
	CONSTRAINT pk_stereotypes PRIMARY KEY (appliesto,stereotype)
)
;
CREATE INDEX ix_stereotypes_stereotype ON t_stereotypes (stereotype ASC)
;
CREATE INDEX ix_stereotypes_eaguid ON t_stereotypes (ea_guid ASC)
;


CREATE TABLE t_taggedvalue
(
	propertyid varchar(40) NOT NULL,
	elementid varchar(40) NOT NULL,
	baseclass varchar(100) NOT NULL,
	tagvalue text,
	notes text,
	CONSTRAINT pk_taggedvalue PRIMARY KEY (propertyid)
)
;
CREATE INDEX ix_taggedvalue_elementid ON t_taggedvalue (elementid ASC)
;


CREATE TABLE t_tasks
(
	taskid integer NOT NULL   DEFAULT NEXTVAL(('taskid_seq'::text)::regclass),
	name varchar(255),
	tasktype varchar(255),
	notes text,
	priority varchar(255),
	status varchar(255),
	owner varchar(255),
	startdate date,
	enddate date,
	phase varchar(50),
	history text,
	percent integer,
	totaltime integer,
	actualtime integer,
	assignedto varchar(100),
	CONSTRAINT pk_tasks PRIMARY KEY (taskid)
)
;

CREATE TABLE t_tcf
(
	tcfid varchar(12) NOT NULL,
	description varchar(50),
	weight real   DEFAULT 1,
	value real   DEFAULT 0,
	notes varchar(255),
	CONSTRAINT pk_tcf PRIMARY KEY (tcfid)
)
;
CREATE INDEX ix_tcf_weight ON t_tcf (weight ASC)
;


CREATE TABLE t_template
(
	templateid varchar(40) NOT NULL,
	templatetype varchar(50) NOT NULL,
	templatename varchar(100) NOT NULL,
	notes varchar(255),
	style varchar(255),
	template text,
	CONSTRAINT pk_template PRIMARY KEY (templateid)
)
;

CREATE TABLE t_testclass
(
	testclass varchar(50) NOT NULL,
	description varchar(50),
	CONSTRAINT pk_testclass PRIMARY KEY (testclass)
)
;

CREATE TABLE t_testplans
(
	planid varchar(50) NOT NULL,
	category varchar(100),
	name varchar(150) NOT NULL,
	author varchar(255),
	notes text,
	testplan text NOT NULL,
	CONSTRAINT pk_testplans PRIMARY KEY (planid)
)
;

CREATE TABLE t_testtypes
(
	testtype varchar(12) NOT NULL,
	description varchar(50),
	numericweight real   DEFAULT 1,
	notes varchar(255),
	CONSTRAINT pk_testtypes PRIMARY KEY (testtype)
)
;
CREATE INDEX ix_testtypes_numericweight ON t_testtypes (numericweight ASC)
;


CREATE TABLE t_trxtypes
(
	description varchar(50),
	numericweight real   DEFAULT 1,
	notes text,
	trx varchar(255),
	trx_id integer NOT NULL   DEFAULT NEXTVAL(('trx_id_seq'::text)::regclass),
	style text,
	CONSTRAINT pk_trxtypes PRIMARY KEY (trx_id)
)
;
CREATE INDEX ix_trxtypes_description ON t_trxtypes (description ASC)
;
CREATE INDEX ix_trxtypes_numericweight ON t_trxtypes (numericweight ASC)
;
CREATE INDEX ix_trxtypes_trx ON t_trxtypes (trx ASC)
;

CREATE TABLE t_umlpattern
(
	patternid integer NOT NULL   DEFAULT NEXTVAL(('patternid_seq'::text)::regclass),
	patterncategory varchar(100),
	patternname varchar(150),
	style varchar(255),
	notes text,
	patternxml text,
	version varchar(50),
	CONSTRAINT pk_umlpattern PRIMARY KEY (patternid)
)
;

CREATE TABLE t_version
(
	elementid varchar(50) NOT NULL,
	versionid varchar(255) NOT NULL,
	elementtype varchar(100) NOT NULL,
	flags varchar(255),
	externalfile varchar(255),
	notes varchar(255),
	owner varchar(255),
	versiondate timestamp without time zone,
	branch varchar(255),
	elementxml text,
	CONSTRAINT pk_version PRIMARY KEY (elementid,versionid)
)
;
CREATE INDEX ix_version_elementid ON t_version (elementid ASC)
;


CREATE TABLE t_xref
(
	xrefid varchar(255) NOT NULL,
	name varchar(255),
	type varchar(255),
	visibility varchar(255),
	namespace varchar(255),
	requirement varchar(255),
	"Constraint" varchar(255),
	behavior varchar(255),
	partition varchar(255),
	description text,
	client varchar(255),
	supplier varchar(255),
	link varchar(255),
	CONSTRAINT pk_xref PRIMARY KEY (xrefid)
)
;
CREATE INDEX ix_xref_client ON t_xref (client ASC)
;
CREATE INDEX ix_xref_supplier ON t_xref (supplier ASC)
;
CREATE INDEX ix_xref_type ON t_xref (type ASC)
;
CREATE INDEX ix_xref_name ON t_xref (name ASC)
;
CREATE INDEX ix_xref_nametype ON t_xref (name ASC,type ASC)
;


CREATE TABLE t_xrefsystem
(
	xrefid varchar(255) NOT NULL,
	name varchar(255),
	type varchar(255),
	visibility varchar(255),
	namespace varchar(255),
	requirement varchar(255),
	"Constraint" varchar(255),
	behavior varchar(255),
	partition varchar(255),
	description text,
	client varchar(255),
	supplier varchar(255),
	link varchar(255),
	toolid varchar(50),
	CONSTRAINT pk_xrefsystem PRIMARY KEY (xrefid)
)
;
CREATE INDEX ix_xrefsystem_client ON t_xrefsystem (client ASC)
;
CREATE INDEX ix_xrefsystem_supplier ON t_xrefsystem (supplier ASC)
;
CREATE INDEX ix_xrefsystem_type ON t_xrefsystem (type ASC)
;


CREATE TABLE t_xrefuser
(
	xrefid varchar(255) NOT NULL,
	name varchar(255),
	type varchar(255),
	namespace varchar(255),
	requirement varchar(255),
	"Constraint" varchar(255),
	behavior varchar(255),
	partition varchar(255),
	description text,
	client varchar(255),
	supplier varchar(255),
	link varchar(255),
	toolid varchar(50),
	visibility varchar(255),
	CONSTRAINT pk_xrefuser PRIMARY KEY (xrefid)
)
;
CREATE INDEX ix_xrefuser_client ON t_xrefuser (client ASC)
;
CREATE INDEX ix_xrefuser_supplier ON t_xrefuser (supplier ASC)
;
CREATE INDEX ix_xrefuser_type ON t_xrefuser (type ASC)
;


CREATE TABLE usys_schema
(
	"V1558" varchar(255) NOT NULL,
	CONSTRAINT "PK_usys_schema" PRIMARY KEY ("V1558")
)
;

CREATE TABLE usys_system
(
	property varchar(50) NOT NULL,
	value varchar(50),
	CONSTRAINT pk_usyssystem PRIMARY KEY (property)
)
;

CREATE TABLE usysoldtables
(
	tablename varchar(50),
	newname varchar(50),
	relorder integer   DEFAULT 0,
	fixcode integer NOT NULL   DEFAULT 0
)
;

CREATE TABLE usysqueries
(
	queryname varchar(50),
	newname varchar(50),
	fixcode integer NOT NULL
)
;

CREATE TABLE usystables
(
	tablename varchar(50) NOT NULL,
	relorder integer   DEFAULT 0,
	displayname varchar(50),
	fromver varchar(50),
	tover varchar(50),
	CONSTRAINT pk_usystables PRIMARY KEY (tablename)
)
;

