services:
  board:
    container_name: board
    build: .
    ports:
      - "8080:3005"
    env_file: "opensource.env"
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: "postgres:latest"
    container_name: postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pgpwd4test
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
  grafana:
    image: "grafana/grafana"
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: true
      GF_AUTH_ANONYMOUS_ORG_ROLE: Editor
    volumes:
      - ./grafana:/etc/grafana/provisioning/datasources
  prometheus:
    image: "prom/prometheus"
    container_name: prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    volumes:
      - ./prometheus:/etc/prometheus
    ports:
      - 9090:9090
