env:
  DB_EA_URL:                "jdbc:postgresql://sparxearepo.database-prod-pg.cloud.vimpelcom.ru:5432/ea_repository"
  DB_EA_USER:               "vault:eafdmmart/data/prod/ea_api#user"
  DB_EA_PASSWORD:           "vault:eafdmmart/data/prod/ea_api#password"
  DB_EA_DATABASE :          "ea_repository"
  IA_GIT_TOKEN:             "vault:eafdmmart/data/prod/ia#token"
  OPENMETADATA_TOKEN:       "vault:eafdmmart/data/prod/OMD#TOKEN"
  OPENMETADATA_URL:         "https://open-metadata.prod.dmp.vimpelcom.ru"
  FDM_URL:                  "jdbc:postgresql://fdm-db.database-prod-pg.cloud.vimpelcom.ru:5432/fdm_db"
  FDM_USERNAME:             "vault:eafdmmart/data/prod/fdm#username"
  FDM_PASSWORD:             "vault:eafdmmart/data/prod/fdm#password"
  GRAFANA_URL:              "https://inside.beeline.ru"
  GRAFANA_TOKEN:            "vault:eafdmmart/data/prod/grafana#token"
  GRAFANA_E2E_TEMPLATE_UID: "2mHJmn5Nk"

ingress:
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 50m
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
