env:
  DB_EA_URL: "vault:eafdmmart/data/test/ea#url"
  DB_EA_USER: "vault:eafdmmart/data/test/ea#username"
  DB_EA_PASSWORD: "vault:eafdmmart/data/test/ea#password"
  DB_EA_DATABASE: "ea_repository"
  IA_GIT_TOKEN: "vault:eafdmmart/data/dev/ia#token"
  OPENMETADATA_TOKEN : "vault:eafdmmart/data/dev/OMD#TOKEN"
  OPENMETADATA_URL : "vault:eafdmmart/data/dev/OMD#URL"
  FDM_URL : "vault:eafdmmart/data/dev/fdm#url"
  FDM_USERNAME : "vault:eafdmmart/data/dev/ea#username"
  FDM_PASSWORD : "vault:eafdmmart/data/dev/ea#password"
  GRAFANA_URL : "vault:eafdmmart/data/dev/grafana#url"
  GRAFANA_TOKEN : "vault:eafdmmart/data/dev/grafana#token"