
const APP_CATALOG_ROOT = process.env.APP_CATALOG_ROOT ?? '{7889FE97-8783-4311-B229-3A88F8EFA8E3}';
const CONTAINER_STEREOTYPE = 'C2';
const API_SPECIFICATION_URL_TAG = 'api_url'

export default { APP_CATALOG_ROOT , CONTAINER_STEREOTYPE, API_SPECIFICATION_URL_TAG}