CREATE TABLE IF NOT EXISTS arch_metrics.PLUGIN_ACTIONS (
    ID BIGSERIAL NOT NULL,	-- Уникальный идентификатор экземпляра счетчика
    VERSION VARCHAR(80) NOT NULL,	-- версия плагина
    ACTION VARCHAR(255) NOT NULL,	-- тип выполняемого действия
    PLUGIN_USER VARCHAR(255),	-- Пользователь плагина
	COUNT BIGINT NOT NULL -- количество выполненых действий
);

CREATE TABLE IF NOT EXISTS arch_metrics.TC_CHANGE_LOG (
	ID SERIAL NOT NULL,
	CODE VARCHAR(255) NOT NULL,
	NAME VARCHAR(255) NOT NULL,
	CHANGE_DATE timestamp NOT NULL
);

ALTER TABLE arch_metrics.PLUGIN_ACTIONS ADD CONSTRAINT PK_PLUGIN_ACTIONS PRIMARY KEY (ID);
ALTER TABLE arch_metrics.PLUGIN_ACTIONS ADD CONSTRAINT PK_ACTION_KEYS UNIQUE  (VERSION,ACTION,PLUGIN_USER);

ALTER TABLE arch_metrics.TC_CHANGE_LOG ADD CONSTRAINT PK_TC_CHANGE_LOG PRIMARY KEY (ID);
