ALTER TABLE arch_metrics.plugin_actions
DROP COLUMN IF EXISTS template;

ALTER TABLE arch_metrics.plugin_actions
ADD COLUMN IF NOT EXISTS template_id VARCHAR(255);

ALTER TABLE arch_metrics.PLUGIN_ACTIONS DROP CONSTRAINT IF EXISTS PK_ACTION_KEYS;

ALTER TABLE arch_metrics.PLUGIN_ACTIONS ADD CONSTRAINT PK_ACTION_KEYS UNIQUE  (VERSION,ACTION,PLUGIN_USER, TEMPLATE_ID);
