const DATA = [
    {
        serverName: null,
        serverType: null,
        serverCode: null,
        clientName: null,
        clientType: null,
        clientCode: null,
        operation: null,
        baseDiagramName: null,
        subDiagramName: null,
        subDiagramDeep: null,
        groupName: "[PRODUCT] Управление продуктовыми каталогом",
        baseProcessName: "ТБД",
        keyProcessName: null,
        processFolder: null,
    },
    {
        serverName: null,
        serverType: null,
        serverCode: null,
        clientName: null,
        clientType: null,
        clientCode: null,
        operation: null,
        baseDiagramName: null,
        subDiagramName: null,
        subDiagramDeep: null,
        groupName: "[REQUEST] Обращения",
        baseProcessName: "[CLAIMS] Претензии",
        keyProcessName: "ТБД",
        processFolder: null,
    },
    {
        serverName: null,
        serverType: null,
        serverCode: null,
        clientName: null,
        clientType: null,
        clientCode: null,
        operation: null,
        baseDiagramName: null,
        subDiagramName: null,
        subDiagramDeep: null,
        groupName: "[REQUEST] Обращения",
        baseProcessName: "[INFO] Консультации",
        keyProcessName: "ТБД",
        processFolder: null,
    },
    {
        serverName: null,
        serverType: null,
        serverCode: null,
        clientName: null,
        clientType: null,
        clientCode: null,
        operation: null,
        baseDiagramName: null,
        subDiagramName: null,
        subDiagramDeep: null,
        groupName: "[SUPPORT] Обслуживание",
        baseProcessName: "[TRANSFER] Переезд",
        keyProcessName: "[FIX] Я, как клиент, хочу перенести домашний интернет на новую квартиру",
        processFolder: null,
    },
    {
        serverName: null,
        serverType: null,
        serverCode: null,
        clientName: null,
        clientType: null,
        clientCode: null,
        operation: null,
        baseDiagramName: null,
        subDiagramName: null,
        subDiagramDeep: null,
        groupName: "[SUPPORT] Обслуживание",
        baseProcessName: "[IMPROVE-MOBILE] Регламент \"Улучшение покрытия мобильной сети для абонентов В2В\"",
        keyProcessName: "ТБД",
        processFolder: null,
    },
    {
        serverName: null,
        serverType: null,
        serverCode: null,
        clientName: null,
        clientType: null,
        clientCode: null,
        operation: null,
        baseDiagramName: null,
        subDiagramName: null,
        subDiagramDeep: null,
        groupName: "[SUPPORT] Обслуживание",
        baseProcessName: "[CTE] Сервисное обслуживание АБО (работа с возвратами, браком, ТВП, расхождениями и прочее)",
        keyProcessName: "ТБД",
        processFolder: null,
    },
    {
        serverName: null,
        serverType: null,
        serverCode: null,
        clientName: null,
        clientType: null,
        clientCode: null,
        operation: null,
        baseDiagramName: null,
        subDiagramName: null,
        subDiagramDeep: null,
        groupName: "[SUPPORT] Обслуживание",
        baseProcessName: "[PIN] Восстановление PIN\\PUK",
        keyProcessName: "[OFFICE] Я, как клиент, хочу разблокировать SIM и восстановить PIN в офисе билайн",
        processFolder: null,
    },
    {
        serverName: null,
        serverType: null,
        serverCode: null,
        clientName: null,
        clientType: null,
        clientCode: null,
        operation: null,
        baseDiagramName: null,
        subDiagramName: null,
        subDiagramDeep: null,
        groupName: "[SUPPORT] Обслуживание",
        baseProcessName: "[PIN] Восстановление PIN\\PUK",
        keyProcessName: "[CALL] Я, как клиент, хочу разбокировать SIM и восстановить PIN звонком по телефону",
        processFolder: null,
    },
    {
        serverName: null,
        serverType: null,
        serverCode: null,
        clientName: null,
        clientType: null,
        clientCode: null,
        operation: null,
        baseDiagramName: null,
        subDiagramName: null,
        subDiagramDeep: null,
        groupName: "[SUPPORT] Обслуживание",
        baseProcessName: "[PIN] Восстановление PIN\\PUK",
        keyProcessName: "[PUK] Я, как клиент, хочу разблокировать SIM и восстановить PIN с использованием PUK кода",
        processFolder: null,
    },
    {
        serverName: null,
        serverType: null,
        serverCode: null,
        clientName: null,
        clientType: null,
        clientCode: null,
        operation: null,
        baseDiagramName: null,
        subDiagramName: null,
        subDiagramDeep: null,
        groupName: "[SUPPORT] Обслуживание",
        baseProcessName: "[LOCK] Добровольная блокировка разблокировка",
        keyProcessName: "[REMOVEFIX] Я, как клиент, хочу разблокировать домашний интернет",
        processFolder: null,
    },
    {
        serverName: null,
        serverType: null,
        serverCode: null,
        clientName: null,
        clientType: null,
        clientCode: null,
        operation: null,
        baseDiagramName: null,
        subDiagramName: null,
        subDiagramDeep: null,
        groupName: "[SUPPORT] Обслуживание",
        baseProcessName: "[LOCK] Добровольная блокировка разблокировка",
        keyProcessName: "[ADDFIX] Я, как клиент, хочу добровольно заблокировать домашиний интернет",
        processFolder: null,
    },
    {
        serverName: null,
        serverType: null,
        serverCode: null,
        clientName: null,
        clientType: null,
        clientCode: null,
        operation: null,
        baseDiagramName: null,
        subDiagramName: null,
        subDiagramDeep: null,
        groupName: "[SUPPORT] Обслуживание",
        baseProcessName: "[LOCK] Добровольная блокировка разблокировка",
        keyProcessName: "[REMOVE] Я, как клиент, хочу разблокировать свой мобильный номер телефона",
        processFolder: null,
    },
    {
        serverName: null,
        serverType: null,
        serverCode: null,
        clientName: null,
        clientType: null,
        clientCode: null,
        operation: null,
        baseDiagramName: null,
        subDiagramName: null,
        subDiagramDeep: null,
        groupName: "[SUPPORT] Обслуживание",
        baseProcessName: "[LOCK] Добровольная блокировка разблокировка",
        keyProcessName: "[ADD] Я, как клиент, хочу добровольно заблокировать свой  мобильный номер телефона",
        processFolder: null,
    },
    {
        serverName: null,
        serverType: null,
        serverCode: null,
        clientName: null,
        clientType: null,
        clientCode: null,
        operation: null,
        baseDiagramName: null,
        subDiagramName: null,
        subDiagramDeep: null,
        groupName: "[SUPPORT] Обслуживание",
        baseProcessName: "[OWNER] Смена владельца номера",
        keyProcessName: "[ORG] Я, как клиент, хочу переформить юрлица номер юр.лица на себя",
        processFolder: null,
    },
    {
        serverName: null,
        serverType: null,
        serverCode: null,
        clientName: null,
        clientType: null,
        clientCode: null,
        operation: null,
        baseDiagramName: null,
        subDiagramName: null,
        subDiagramDeep: null,
        groupName: "[SUPPORT] Обслуживание",
        baseProcessName: "[OWNER] Смена владельца номера",
        keyProcessName: "[IDENTIFY] Я, как клиент, хочу переформить мобильный номер на себя с альтернативной идентификацией",
        processFolder: null,
    },
    {
        serverName: null,
        serverType: null,
        serverCode: null,
        clientName: null,
        clientType: null,
        clientCode: null,
        operation: null,
        baseDiagramName: null,
        subDiagramName: null,
        subDiagramDeep: null,
        groupName: "[SUPPORT] Обслуживание",
        baseProcessName: "[OWNER] Смена владельца номера",
        keyProcessName: "[INDIVIDUAL] Я, как клиент, хочу переормить мобильный номер другого человека на себя",
        processFolder: null,
    },
    {
        serverName: null,
        serverType: null,
        serverCode: null,
        clientName: null,
        clientType: null,
        clientCode: null,
        operation: null,
        baseDiagramName: null,
        subDiagramName: null,
        subDiagramDeep: null,
        groupName: "[SUPPORT] Обслуживание",
        baseProcessName: "[INFO] Изменение/подтверждение персональных данных",
        keyProcessName: "[CONTRACT] я, как клиент изменяю данные по договору/клиенту (изменение ИНН, наименования, КПП, адреса, контактного лица и прочее)",
        processFolder: null,
    },
    {
        serverName: null,
        serverType: null,
        serverCode: null,
        clientName: null,
        clientType: null,
        clientCode: null,
        operation: null,
        baseDiagramName: null,
        subDiagramName: null,
        subDiagramDeep: null,
        groupName: "[SUPPORT] Обслуживание",
        baseProcessName: "[INFO] Изменение/подтверждение персональных данных",
        keyProcessName: "[OFFICE] Я, как клиент, хочу обновить персональные данные в офисе билайн",
        processFolder: null,
    },
    {
        serverName: null,
        serverType: null,
        serverCode: null,
        clientName: null,
        clientType: null,
        clientCode: null,
        operation: null,
        baseDiagramName: null,
        subDiagramName: null,
        subDiagramDeep: null,
        groupName: "[SUPPORT] Обслуживание",
        baseProcessName: "[INFO] Изменение/подтверждение персональных данных",
        keyProcessName: "[ESIA] Я, как клиент, хочу обновить персональные данные через ГОСУСЛУГИ",
        processFolder: null,
    },
    {
        serverName: null,
        serverType: null,
        serverCode: null,
        clientName: null,
        clientType: null,
        clientCode: null,
        operation: null,
        baseDiagramName: null,
        subDiagramName: null,
        subDiagramDeep: null,
        groupName: "[SUPPORT] Обслуживание",
        baseProcessName: "[DEVICE] Замена SIM и номера",
        keyProcessName: "[SIM] Я,  как  клиент, хочу поменять SIM карту",
        processFolder: null,
    },
    {
        serverName: null,
        serverType: null,
        serverCode: null,
        clientName: null,
        clientType: null,
        clientCode: null,
        operation: null,
        baseDiagramName: null,
        subDiagramName: null,
        subDiagramDeep: null,
        groupName: "[SUPPORT] Обслуживание",
        baseProcessName: "[DEVICE] Замена SIM и номера",
        keyProcessName: "[MSISDN] Я,  как клиент, хочу поменять номер телефона",
        processFolder: null,
    },
    {
        serverName: null,
        serverType: null,
        serverCode: null,
        clientName: null,
        clientType: null,
        clientCode: null,
        operation: null,
        baseDiagramName: null,
        subDiagramName: null,
        subDiagramDeep: null,
        groupName: "[SUPPORT] Обслуживание",
        baseProcessName: "[ACCOUNT] Управление аккаунтами",
        keyProcessName: "[APP] Я, как клиент, хчоу добавить аккаунт для управления в мобильном приложении",
        processFolder: null,
    },
    {
        serverName: null,
        serverType: null,
        serverCode: null,
        clientName: null,
        clientType: null,
        clientCode: null,
        operation: null,
        baseDiagramName: null,
        subDiagramName: null,
        subDiagramDeep: null,
        groupName: "[SUPPORT] Обслуживание",
        baseProcessName: "[ACCOUNT] Управление аккаунтами",
        keyProcessName: "[ELK] Я, как клиент, хочу добавить аккаунт для управления в ЕЛК",
        processFolder: null,
    },
    {
        serverName: null,
        serverType: null,
        serverCode: null,
        clientName: null,
        clientType: null,
        clientCode: null,
        operation: null,
        baseDiagramName: null,
        subDiagramName: null,
        subDiagramDeep: null,
        groupName: "[SUPPORT] Обслуживание",
        baseProcessName: "[FAMALY] Семья в билайн",
        keyProcessName: "[INFO] Я, как клиент, хочу получить информацию о балансах близких",
        processFolder: null,
    },
    {
        serverName: null,
        serverType: null,
        serverCode: null,
        clientName: null,
        clientType: null,
        clientCode: null,
        operation: null,
        baseDiagramName: null,
        subDiagramName: null,
        subDiagramDeep: null,
        groupName: "[SUPPORT] Обслуживание",
        baseProcessName: "[FAMALY] Семья в билайн",
        keyProcessName: "[SHARE] Я, как клиент, хочу поделиться тарифом с близкими",
        processFolder: null,
    },
    {
        serverName: null,
        serverType: null,
        serverCode: null,
        clientName: null,
        clientType: null,
        clientCode: null,
        operation: null,
        baseDiagramName: null,
        subDiagramName: null,
        subDiagramDeep: null,
        groupName: "[SUPPORT] Обслуживание",
        baseProcessName: "[FAMALY] Семья в билайн",
        keyProcessName: "[INCLUDE] Я, как клиент, хоче подключить близких в в Семью билайн",
        processFolder: null,
    },
    {
        serverName: null,
        serverType: null,
        serverCode: null,
        clientName: null,
        clientType: null,
        clientCode: null,
        operation: null,
        baseDiagramName: null,
        subDiagramName: null,
        subDiagramDeep: null,
        groupName: "[SUPPORT] Обслуживание",
        baseProcessName: "[FAMALY] Семья в билайн",
        keyProcessName: "[SUBSCRIBE] Я, как клиент, хочу подключить подписку Все для семьи",
        processFolder: null,
    },
    {
        serverName: null,
        serverType: null,
        serverCode: null,
        clientName: null,
        clientType: null,
        clientCode: null,
        operation: null,
        baseDiagramName: null,
        subDiagramName: null,
        subDiagramDeep: null,
        groupName: "[SUPPORT] Обслуживание",
        baseProcessName: "[SERVICE] Подключение/отключение услуг",
        keyProcessName: "[CONVERGENT] Я, как клиент, хочу поменять условия конвергентного тарифного плана",
        processFolder: null,
    },
    {
        serverName: null,
        serverType: null,
        serverCode: null,
        clientName: null,
        clientType: null,
        clientCode: null,
        operation: null,
        baseDiagramName: null,
        subDiagramName: null,
        subDiagramDeep: null,
        groupName: "[SUPPORT] Обслуживание",
        baseProcessName: "[SERVICE] Подключение/отключение услуг",
        keyProcessName: "[FIX] Я, как клиент, хочу подключить или отключить услугу фиксированной связи",
        processFolder: null,
    },
    {
        serverName: null,
        serverType: null,
        serverCode: null,
        clientName: null,
        clientType: null,
        clientCode: null,
        operation: null,
        baseDiagramName: null,
        subDiagramName: null,
        subDiagramDeep: null,
        groupName: "[SUPPORT] Обслуживание",
        baseProcessName: "[SERVICE] Подключение/отключение услуг",
        keyProcessName: "[MOBILE] Я, как клиент, хочу подключить или отключить услугу на мобильном тарифном плане",
        processFolder: null,
    },
    {
        serverName: null,
        serverType: null,
        serverCode: null,
        clientName: null,
        clientType: null,
        clientCode: null,
        operation: null,
        baseDiagramName: null,
        subDiagramName: null,
        subDiagramDeep: null,
        groupName: "[SUPPORT] Обслуживание",
        baseProcessName: "[TARIF] Смена тарифного плана",
        keyProcessName: "[CONVERGENT] Я, как клиент, хочу поменять условия конвергентного тарифного плана",
        processFolder: null,
    },
    {
        serverName: null,
        serverType: null,
        serverCode: null,
        clientName: null,
        clientType: null,
        clientCode: null,
        operation: null,
        baseDiagramName: null,
        subDiagramName: null,
        subDiagramDeep: null,
        groupName: "[SUPPORT] Обслуживание",
        baseProcessName: "[TARIF] Смена тарифного плана",
        keyProcessName: "[FIX] Я, как клиент, хочу сменить тарифный план на домашний интернет и ТВ",
        processFolder: null,
    },
    {
        serverName: null,
        serverType: null,
        serverCode: null,
        clientName: null,
        clientType: null,
        clientCode: null,
        operation: null,
        baseDiagramName: null,
        subDiagramName: null,
        subDiagramDeep: null,
        groupName: "[SUPPORT] Обслуживание",
        baseProcessName: "[TARIF] Смена тарифного плана",
        keyProcessName: "[MOBILE] Я, как клиент, хочу сменить мобильный тарифный план",
        processFolder: "[МП]",
    },
    {
        serverName: "Мобильное приложение \"Мой Билайн\"/APP",
        serverType: "ProvidedInterface",
        serverCode: "MOBILEAPP",
        clientName: "Output",
        clientType: "MessageEndpoint",
        clientCode: null,
        operation: null,
        baseDiagramName: "2.5 Я, как клиент, перехожу на тарифный план UP в мобильном приложении",
        subDiagramName: "2.5 Я, как клиент, перехожу на тарифный план UP в мобильном приложении",
        subDiagramDeep: 0,
        groupName: "[SUPPORT] Обслуживание",
        baseProcessName: "[TARIF] Смена тарифного плана",
        keyProcessName: "[MOBILE] Я, как клиент, хочу сменить мобильный тарифный план",
        processFolder: "2.5 Я, как клиент, меняю тарифный план UP в мобильном приложении",
    },
    {
        serverName: "Мобильное приложение \"Мой Билайн\"/REST API BE",
        serverType: "ProvidedInterface",
        serverCode: "MOBILEAPP",
        clientName: "Мобильное приложение \"Мой Билайн\"",
        clientType: "Component",
        clientCode: "MOBILEAPP",
        operation: null,
        baseDiagramName: "2.5 Я, как клиент, перехожу на тарифный план UP в мобильном приложении",
        subDiagramName: "2.5 Я, как клиент, перехожу на тарифный план UP в мобильном приложении",
        subDiagramDeep: 0,
        groupName: "[SUPPORT] Обслуживание",
        baseProcessName: "[TARIF] Смена тарифного плана",
        keyProcessName: "[MOBILE] Я, как клиент, хочу сменить мобильный тарифный план",
        processFolder: "2.5 Я, как клиент, меняю тарифный план UP в мобильном приложении",
    }
]

export default DATA;

module.exports = DATA;